layout_width: 4
button_size: 14
margin: 8

buttons:

	hide:
		action: hide
		size: 4,1
		icon: minus
		style: shy
		text: "hide"
		visibility: docked

	prev_desktop:
		action: win+ctrl+left
		size: 2,1
		icon: chevron_triple_left
		style: shy
		text: previous desktop
	next_desktop:
		action: win+ctrl+right
		size: 2,1
		icon: chevron_triple_right
		style: shy 
		text: next desktop

	undo:
		action: ctrl+z
		size: 2,2
		style: accent
		icon: undo
		text: undo
	redo:
		action: ctrl+y
		size: 2,2
		style: accent
		icon: redo
		text: redo

	docked_spacer1:
		spacer: true
		visibility: docked
		size: 4,1
	
	copy:
		action: ctrl+c
		size: 2,2
		style: outlined
		icon: content_copy
		text: copy
	paste:
		action: ctrl+v
		size: 2,2
		style: outlined
		icon: content_paste
		text: paste
	cut:
		action: ctrl+x
		size: 2,2
		icon_stretch: none
		style: outlined
		icon: content_cut
		text: cut
	select_all:
		action: ctrl+a
		size: 2,2
		icon: card_text
		text: select all
		style: outlined

	docked_spacer2:
		spacer: true
		visibility: docked
		size: 4,1

	enter:
		action: enter
		size: 2,2
		style: outlined
		icon: subdirectory_arrow_left
	escape:
		font_weight: 500
		action: escape
		size: 2,2
		style: outlined
		text: Esc

	docked_spacer3:
		spacer: true
		visibility: docked
		size: 4,1

	shift:
		action: toggle shift
		size: 2,2
		text: toggle shift
		icon: apple_keyboard_shift
	space:
		action: toggle space
		size: 2,2
		text: toggle space
		icon: keyboard_space
	ctrl:
		action: toggle ctrl
		size: 2,2
		text: toggle ctrl
		icon: apple_keyboard_control
	alt:
		action: toggle alt
		size: 2,2
		text: toggle alt
		icon: apple_keyboard_option

	docked_spacer4:
		spacer: true
		visibility: docked
		size: 4,1


	left:
		action: repeat left
		size: 1,2
		icon: chevron_left
		visibility: docked
	up:
		action: repeat up
		size: 2,1
		icon: chevron_up
		visibility: docked
	right:
		action: repeat right
		size: 1,2
		icon: chevron_right
		visibility: docked
	down:
		action: repeat down
		size: 2,1
		icon: chevron_down
		visibility: docked

	docked_spacer5:
		spacer: true
		visibility: docked
		size: 4,1

	dock_left:
		action: win+left
		size: 2,2
		icon: dock_left
		visibility: docked
	dock_right:
		action: win+right
		size: 2,2
		icon: dock_right
		visibility: docked
	dock_up:
		action: win+up
		size: 2,2
		icon: dock_top
		visibility: docked
	dock_down:
		action: win+down
		size: 2,2
		icon: dock_bottom
		visibility: docked


	docked_spacer6:
		spacer: true
		visibility: docked
		size: 4,1

	play_pause:
		action: media_play_pause
		size: 4,2
		style: outlined
		icon: play_pause
		visibility: docked
	prev_track:
		action: media_previous_track
		size: 2,2
		style: outlined
		icon: skip_previous
		visibility: docked
	next_track:
		action: media_next_track
		size: 2,2
		style: outlined
		icon: skip_next
		visibility: docked

	docked_spacer7:
		spacer: true
		visibility: docked
		size: 4,1


	docked_spacer6:
		spacer: true
		visibility: docked
		size: 4,1

	save:
		action: ctrl+s
		size: 2,2
		style: outlined
		icon: content_save
		text: save
	new:
		action: ctrl+n
		size: 2,2
		style: outlined
		icon: file
		text: new
